trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: myStage
  type: string
  default: 'Etapas_Stage'
- name: myJob
  type: string
  default: 'Job1'
- name: myString
  type: string
  default: 'ValorPorDefecto'
- name: mynum
  displayName: 'MyNumeroDeParametro'
  type: number
  default: 123

- name: miOpcionDeEntorno # Este es el nombre "interno" para los desarrolladores
  displayName: 'Elige tu Entorno de Despliegue' # ¡Esto es lo que tú verías!
  type: string # Indica que es un tipo de "texto"
  default: 'Desarrollo' # El valor que se usa si no eliges nada
  values: # Las opciones que puedes seleccionar
    - 'Desarrollo'
    - 'Pruebas'
    - 'Producción'

stages:
- stage: ${{ parameters.myStage }}
  jobs: 
  - job: 
    steps:
    - script: echo ${{ parameters.myString }} was entered at runtime!
    - ${{ if not(eq(parameters.mynum, 123)) }}:
      - script: echo You overrode the default number to ${{ parameters.mynum }}
