parameters:
- name: myStage
  type: string
  default: 'Etapas (Stage)'
- name: myJob
  type: string
  default: 'Job1'
- name: myString
  type: string
  default: 'Valor por defecto'
- name: mynum
  displayName: 'My numero de parametro'
  type: number
  default: 123
  
stages:
- stage: ${{ parameters.myStage }}
  jobs: 
  - job: 
    steps:
    - script: echo ${{ parameters.myString }} was entered at runtime!
    - ${{ if not(eq(parameters.mynum, 123)) }}:
      - script: echo You overrode the default number to ${{ parameters.mynum }}
